### ISSUE TITLE
User Auth (Signup, Login, Logout)

### ISSUE THREAD

**Issue by kgilles** [sublinks/sublinks-frontend#13]
Create page where the user can sign up and log in.

Store user auth in cookies.

Connect signup and login page(s) to the API.

Add logout option to Profile menu and connect to API.

**Comment by kgilles** [comment]
Removing sign-up page from this ticket as it's already too much work just getting login and auth stuff connected.
Moving that to #77

**Comment by chasingtheflow** [comment]
Is there a log in that can be used for dev purposes?

**Comment by kgilles** [comment]
> Is there a log in that can be used for dev purposes?

@chasingtheflow If you run the Docker dev setup it'll create 20 test users plus an admin user. All can be used for testing.

Example username is "bill" and password for all of them is `password123`

**Comment by chasingtheflow** [comment]
Thanks!
