### ISSUE TITLE
s/join-lemmy.org/sublinks.org/

### ISSUE THREAD

**Issue by maltfield** [sublinks/sublinks-frontend#143]
Currently demo.sublinks.org links to join-lemmy.org

 * https://demo.sublinks.org/

We should probably change all references to "join-lemmy.org" to be "sublinks.org"

**Comment by jgrim** [comment]
We're temporarily using the Lemmy UI while we develop the Sublinks Official UI and API. We won't modify their front end to give the illusion that we developed that UI. I understand your concern; however, I do not plan to modify their code.

**Comment by maltfield** [comment]
Perhaps you could host Lemmy at some other subdomain?

And replace `demo.sublinks.org` with `Coming soon`?
